export const ALERT_TOKEN = 'ALERT_TOKEN';
export const EMAIL_FROM_TOKEN = 'EMAIL_FROM_TOKEN';
export const EMAIL_TO_TOKEN = 'EMAIL_TO_TOKEN';
export const EMAIL_SERVICE_TOKEN = 'EMAIL_SERVICE_TOKEN';
export const EMAIL_USER_TOKEN = 'EMAIL_USER_TOKEN';
export const EMAIL_PASSWORD_TOKEN = 'EMAIL_PASSWORD_TOKEN';
